name: Publish Docker images

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: ghcr.io/michaelholley/murl-service
            context: packages/service
          - image: ghcr.io/michaelholley/murl-web-client
            context: packages/web-client
    steps:
      - uses: actions/checkout@v6
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ matrix.image }}:latest
          labels: org.opencontainers.image.source=https://github.com/${{ github.repository }}
